/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Utileria;

import Controlador.ControladorConfiguracion;
import Objeto.ObjetoConfiguracion;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author KSGAMER
 */
public class Configuracion extends java.awt.Dialog {

    private ControladorConfiguracion configuracion = new ControladorConfiguracion();
    /**
     * Creates new form Configuracion
     *
     * @param parent
     * @param modal
     */
    public Configuracion(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        this.setOpacity(0f);
        this.setLocationRelativeTo(null);
        configuracionInicial();
        this.setVisible(true);
    }
    
    public void configuracionInicial() {
        txtBaseDatos.setText(configuracion.configuracion().getBase_datos());
        txtContraseña.setText(configuracion.configuracion().getContraseña());
        txtInstancia.setText(configuracion.configuracion().getInstancia());
        txtPuerto.setText(String.valueOf(configuracion.configuracion().getPuerto()));
        txtServidor.setText(configuracion.configuracion().getServidor());
        txtUsuario.setText(configuracion.configuracion().getUsuario());
    }

    public void animacionAbrir() {
        for (double i = 0; i <= 1; i += 0.01225) {
            try {
                this.setOpacity((float) i);
                Thread.sleep(2);
            } catch (InterruptedException ex) {
                Logger.getLogger(Configuracion.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }

    public void animacionCerrar() {
        for (double i = 0.9; i >= 0; i -= 0.01225) {
            try {
                this.setOpacity((float) i);
                Thread.sleep(2);
            } catch (InterruptedException ex) {
                Logger.getLogger(Mensaje.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        this.setVisible(false);
        this.dispose();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        txtServidor = new javax.swing.JTextField();
        txtInstancia = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtBaseDatos = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtPuerto = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtContraseña = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txtUsuario = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setMinimumSize(new java.awt.Dimension(375, 460));
        setUndecorated(true);
        setSize(new java.awt.Dimension(375, 460));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(31, 31, 31));
        jPanel1.setLayout(null);

        jLabel1.setBackground(new java.awt.Color(220, 24, 24));
        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Cancelar");
        jLabel1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel1.setOpaque(true);
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel1);
        jLabel1.setBounds(210, 410, 150, 30);

        jLabel2.setBackground(new java.awt.Color(38, 144, 48));
        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Aceptar");
        jLabel2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabel2.setOpaque(true);
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel2);
        jLabel2.setBounds(20, 410, 150, 30);

        jLabel3.setBackground(new java.awt.Color(255, 255, 255));
        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Configuración de la Conexión");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(0, 0, 375, 40);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(null);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel4.setText("SERVIDOR:");
        jPanel2.add(jLabel4);
        jLabel4.setBounds(20, 30, 340, 14);

        txtServidor.setText("jTextField1");
        jPanel2.add(txtServidor);
        txtServidor.setBounds(20, 45, 340, 25);

        txtInstancia.setText("jTextField1");
        jPanel2.add(txtInstancia);
        txtInstancia.setBounds(20, 95, 340, 25);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel5.setText("INSTANCIA:");
        jPanel2.add(jLabel5);
        jLabel5.setBounds(20, 80, 340, 14);

        txtBaseDatos.setText("jTextField1");
        jPanel2.add(txtBaseDatos);
        txtBaseDatos.setBounds(20, 195, 340, 25);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel6.setText("BASE DE DATOS:");
        jPanel2.add(jLabel6);
        jLabel6.setBounds(20, 180, 340, 14);

        txtPuerto.setText("jTextField1");
        jPanel2.add(txtPuerto);
        txtPuerto.setBounds(20, 145, 340, 25);

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel7.setText("PUERTO:");
        jPanel2.add(jLabel7);
        jLabel7.setBounds(20, 130, 340, 14);

        txtContraseña.setText("jTextField1");
        jPanel2.add(txtContraseña);
        txtContraseña.setBounds(20, 295, 340, 25);

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel8.setText("CONTRASEÑA:");
        jPanel2.add(jLabel8);
        jLabel8.setBounds(20, 280, 340, 14);

        txtUsuario.setText("jTextField1");
        jPanel2.add(txtUsuario);
        txtUsuario.setBounds(20, 245, 340, 25);

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel9.setText("USUARIO:");
        jPanel2.add(jLabel9);
        jLabel9.setBounds(20, 230, 340, 14);

        jPanel1.add(jPanel2);
        jPanel2.setBounds(0, 40, 375, 350);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 375, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 460, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        setVisible(false);
        this.dispose();
    }//GEN-LAST:event_formWindowClosing

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        new Thread() {
            public void run() {
                animacionAbrir();
            }
        }.start();
    }//GEN-LAST:event_formWindowOpened

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
        new Thread() {
            public void run() {
                animacionCerrar();
            }
        }.start();
    }//GEN-LAST:event_jLabel1MouseClicked

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
        new Thread() {
           public void run() {
               configuracion.actualizarConfiguracion(new ObjetoConfiguracion(txtServidor.getText(), txtInstancia.getText(), Integer.parseInt(txtPuerto.getText()), txtBaseDatos.getText(), txtUsuario.getText(), txtContraseña.getText()));
               animacionCerrar();
           }
        }.start();
    }//GEN-LAST:event_jLabel2MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Configuracion dialog = new Configuracion(new java.awt.Frame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField txtBaseDatos;
    private javax.swing.JTextField txtContraseña;
    private javax.swing.JTextField txtInstancia;
    private javax.swing.JTextField txtPuerto;
    private javax.swing.JTextField txtServidor;
    private javax.swing.JTextField txtUsuario;
    // End of variables declaration//GEN-END:variables
}
