/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import Controlador.ControladorHabitacion;
import Controlador.ControladorReservacion;
import Objeto.ObjetoHabitacion;
import Objeto.ObjetoReservacion;

/**
 *
 * @author KSGAMER
 */
public class Cobros extends javax.swing.JPanel {
    private ControladorHabitacion habitaciones;
    private ControladorReservacion reservaciones;
    private Principal principal;
    private String habitacionID;
    private int reservacionID;
    /**
     * Creates new form Cobros
     * @param principal
     */
    public Cobros(Principal principal) {
        initComponents();
        this.principal = principal;
        this.setBounds(0, 0, 1100, 670);
        configuracionInicial();
    }
    
    public void configuracionInicial() {
        notificacion.setVisible(false);
    }
    
    public void habitacionSeleccionada(String habitacion, int reservacion) {
        habitacionID = habitacion;
        reservacionID = reservacion;
    }
    
    public void cargarDatos() {
        habitaciones = new ControladorHabitacion();
        reservaciones = new ControladorReservacion();
        this.habitaciones.listaHabitaciones().stream().filter((habitacion) -> (habitacion.getHabitacionID().equals(habitacionID))).forEachOrdered((habitacion) -> {
            lbHabitacion.setText(habitacion.getHabitacionID());
            lbCategoria.setText(habitacion.getCategoriaID());
            lbPiso.setText(habitacion.getPisoID());
            lbCaracteristicas.setText("<html>"+habitacion.getCaracteristicas()+"</html>");
        });
        for (ObjetoReservacion reservacion : this.reservaciones.listaReservaciones()) {
            if(reservacion.getReservacionID() == reservacionID) {
                lbFechaIngreso.setText(reservacion.getFechaIngreso().toString());
                lbFechaSalida.setText(reservacion.getFechaSalida().toString());
                lbCliente.setText(reservacion.getClienteID());
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        regresar = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        notificacion = new javax.swing.JPanel();
        mensaje = new javax.swing.JLabel();
        cerrarNotificacion = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        lbHabitacion = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        lbFechaIngreso = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        lbFechaSalida = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        lbCliente = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        lbCategoria = new javax.swing.JLabel();
        lbPiso = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        lbCaracteristicas = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        lbCargar = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(null);

        jPanel3.setBackground(new java.awt.Color(106, 150, 176));
        jPanel3.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText(" Módulo de Cobros");
        jPanel3.add(jLabel1);
        jLabel1.setBounds(0, 0, 1060, 40);

        regresar.setBackground(new java.awt.Color(0, 153, 255));
        regresar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        regresar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagen/Principal/regresar-20.png"))); // NOI18N
        regresar.setToolTipText("Regresar a reservaciones");
        regresar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        regresar.setOpaque(true);
        regresar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                regresarMouseClicked(evt);
            }
        });
        jPanel3.add(regresar);
        regresar.setBounds(1060, 0, 40, 40);

        jPanel2.add(jPanel3);
        jPanel3.setBounds(0, 0, 1100, 40);

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setLayout(null);

        notificacion.setBackground(new java.awt.Color(220, 24, 24));
        notificacion.setLayout(null);

        mensaje.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        mensaje.setForeground(new java.awt.Color(255, 255, 255));
        mensaje.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        mensaje.setText("jLabel7");
        notificacion.add(mensaje);
        mensaje.setBounds(0, 0, 1075, 20);

        cerrarNotificacion.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        cerrarNotificacion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagen/Principal/cerrarNotificacion-16.png"))); // NOI18N
        cerrarNotificacion.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        cerrarNotificacion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cerrarNotificacionMouseClicked(evt);
            }
        });
        notificacion.add(cerrarNotificacion);
        cerrarNotificacion.setBounds(1080, 0, 20, 20);

        jPanel4.add(notificacion);
        notificacion.setBounds(0, 606, 1100, 20);

        jPanel5.setLayout(null);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setText("Habitación:");
        jPanel5.add(jLabel2);
        jLabel2.setBounds(20, 40, 80, 15);

        lbHabitacion.setText("Nombre de la habitación");
        jPanel5.add(lbHabitacion);
        lbHabitacion.setBounds(20, 60, 300, 20);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setText("Fecha de Ingreso:");
        jPanel5.add(jLabel3);
        jLabel3.setBounds(20, 360, 120, 15);

        lbFechaIngreso.setText("Fecha de ingreso de la reservación");
        jPanel5.add(lbFechaIngreso);
        lbFechaIngreso.setBounds(20, 380, 300, 20);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setText("Fecha de Salida:");
        jPanel5.add(jLabel4);
        jLabel4.setBounds(20, 420, 120, 15);

        lbFechaSalida.setText("Fecha de salida de la reservación");
        jPanel5.add(lbFechaSalida);
        lbFechaSalida.setBounds(20, 440, 300, 20);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel5.setText("Cliente:");
        jPanel5.add(jLabel5);
        jLabel5.setBounds(20, 480, 120, 15);

        lbCliente.setText("Nombre del cliente");
        jPanel5.add(lbCliente);
        lbCliente.setBounds(20, 500, 300, 20);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel6.setText("Categoria:");
        jPanel5.add(jLabel6);
        jLabel6.setBounds(20, 100, 70, 15);

        lbCategoria.setText("Nombre de la categoria");
        jPanel5.add(lbCategoria);
        lbCategoria.setBounds(20, 120, 300, 20);

        lbPiso.setText("Nombre del piso");
        jPanel5.add(lbPiso);
        lbPiso.setBounds(20, 180, 300, 20);

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel7.setText("Piso:");
        jPanel5.add(jLabel7);
        jLabel7.setBounds(20, 160, 40, 15);

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel8.setText("Caracteristicas:");
        jPanel5.add(jLabel8);
        jLabel8.setBounds(20, 220, 100, 15);

        lbCaracteristicas.setText("Nombre del piso");
        lbCaracteristicas.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jPanel5.add(lbCaracteristicas);
        lbCaracteristicas.setBounds(20, 240, 300, 100);

        jPanel4.add(jPanel5);
        jPanel5.setBounds(30, 30, 340, 560);

        jPanel2.add(jPanel4);
        jPanel4.setBounds(0, 40, 1100, 630);

        jPanel1.setLayout(null);

        lbCargar.setBackground(new java.awt.Color(45, 144, 54));
        lbCargar.setOpaque(true);
        jPanel1.add(lbCargar);
        lbCargar.setBounds(0, 0, 0, 4);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1100, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 1100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 670, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 4, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, 0)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 666, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void regresarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_regresarMouseClicked
//        cancelar();
        principal.reservaciones(habitacionID);
        principal.habitacionReservada(habitacionID);
    }//GEN-LAST:event_regresarMouseClicked

    private void cerrarNotificacionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cerrarNotificacionMouseClicked
//        cerrarNotificacion();
    }//GEN-LAST:event_cerrarNotificacionMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel cerrarNotificacion;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JLabel lbCaracteristicas;
    private javax.swing.JLabel lbCargar;
    private javax.swing.JLabel lbCategoria;
    private javax.swing.JLabel lbCliente;
    private javax.swing.JLabel lbFechaIngreso;
    private javax.swing.JLabel lbFechaSalida;
    private javax.swing.JLabel lbHabitacion;
    private javax.swing.JLabel lbPiso;
    private javax.swing.JLabel mensaje;
    private javax.swing.JPanel notificacion;
    private javax.swing.JLabel regresar;
    // End of variables declaration//GEN-END:variables
}
