/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import Controlador.ControladorCampos;
import Controlador.ControladorEncriptacion;
import Controlador.ControladorLogitudCampos;
import Controlador.ControladorUsuario;
import Utileria.Configuracion;
import java.awt.Color;
import java.awt.Cursor;
import java.awt.event.ItemEvent;
import java.awt.event.KeyEvent;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author KSGAMER
 */
public class Sesion extends javax.swing.JFrame {

    public static boolean sesion = false;
    private Thread carga;

    /**
     * Creates new form VistaSesion
     */
    public Sesion() {
        initComponents();
        configuracionInicial();
    }

    public void cargar(int contador) {
        lbcargar.setVisible(true);
        setCursor(new Cursor(Cursor.WAIT_CURSOR));
        carga = new Thread() {
            public void run() {
                for (int i = contador; i <= 300; i++) {
                    try {
                        lbcargar.setBounds(0, 370, i, 4);
                        sleep(Math.round(Math.random() * 110));
                    } catch (InterruptedException ex) {
                        Logger.getLogger(Sesion.class.getName()).log(Level.SEVERE, null, ex);
                    }
                }
            }
        };
        carga.start();
    }

    public void animacionCerrar() {
        for (double i = 1; i >= 0; i -= 0.01) {
            try {
                this.setOpacity((float) i);
                Thread.sleep(2);
            } catch (InterruptedException ex) {
                Logger.getLogger(Sesion.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }

    public void notificacion(boolean bandera) {
        this.notificacionBD.setVisible(bandera);
        this.notificacionBD1.setVisible(bandera);
    }

    private void configuracionInicial() {
        this.derecha.setBackground(Color.decode("#1486F5"));
        notificacion(!BD.BD.verificarConexion);
        lbcargar.setBounds(0, 370, 0, 4);
    }

    public void autentificacion() {
        cargar(0);
        autentificar.setEnabled(false);
        new ControladorUsuario().autentificacion(txtUsuario.getText(), new ControladorEncriptacion().encriptar(String.valueOf(txtContraseña.getPassword())), notificacion, this);
        notificacion(!BD.BD.verificarConexion);
        autentificar.setEnabled(true);
        carga.stop();
        setCursor(new Cursor(Cursor.DEFAULT_CURSOR));
        lbcargar.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        notificacionBD = new javax.swing.JPanel();
        CerrarNotificacion = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        izquierda = new javax.swing.JPanel();
        cerrar = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtUsuario = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtContraseña = new javax.swing.JPasswordField();
        notificacion = new javax.swing.JLabel();
        configuracion = new javax.swing.JLabel();
        minimizar = new javax.swing.JLabel();
        lbcargar = new javax.swing.JLabel();
        Mostrar = new javax.swing.JCheckBox();
        autentificar = new principal.MaterialButton();
        derecha = new javax.swing.JPanel();
        notificacionBD1 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        SesionImagen = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Login");
        setMinimumSize(new java.awt.Dimension(600, 374));
        setUndecorated(true);
        getContentPane().setLayout(null);

        notificacionBD.setBackground(new java.awt.Color(220, 24, 24));
        notificacionBD.setInheritsPopupMenu(true);
        notificacionBD.setLayout(null);

        CerrarNotificacion.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        CerrarNotificacion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagen/Sesion/cerrarNotificacion-16.png"))); // NOI18N
        CerrarNotificacion.setToolTipText("Cerrar Notificación");
        CerrarNotificacion.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        CerrarNotificacion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CerrarNotificacionMouseClicked(evt);
            }
        });
        notificacionBD.add(CerrarNotificacion);
        CerrarNotificacion.setBounds(580, 0, 20, 20);

        jLabel8.setBackground(new java.awt.Color(220, 24, 24));
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("Error al intentar conectar a Base de Datos verifique su conexión");
        jLabel8.setPreferredSize(new java.awt.Dimension(500, 14));
        notificacionBD.add(jLabel8);
        jLabel8.setBounds(0, 0, 600, 20);

        getContentPane().add(notificacionBD);
        notificacionBD.setBounds(0, 355, 600, 20);

        izquierda.setBackground(new java.awt.Color(255, 255, 255));
        izquierda.setLayout(null);

        cerrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagen/Sesion/cerrar-16.png"))); // NOI18N
        cerrar.setToolTipText("Cerrar");
        cerrar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        cerrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cerrarMouseClicked(evt);
            }
        });
        izquierda.add(cerrar);
        cerrar.setBounds(278, 5, 16, 16);

        jLabel2.setFont(new java.awt.Font("Segoe UI Symbol", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(62, 118, 168));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("<html>Inicio de Sesión</html>");
        izquierda.add(jLabel2);
        jLabel2.setBounds(10, 66, 280, 20);

        txtUsuario.setText("Ingresa un usuario");
        txtUsuario.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtUsuarioFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtUsuarioFocusLost(evt);
            }
        });
        txtUsuario.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtUsuarioKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtUsuarioKeyTyped(evt);
            }
        });
        izquierda.add(txtUsuario);
        txtUsuario.setBounds(60, 140, 200, 25);

        jLabel3.setBackground(new java.awt.Color(31, 184, 184));
        jLabel3.setOpaque(true);
        jLabel3.setPreferredSize(new java.awt.Dimension(9, 0));
        izquierda.add(jLabel3);
        jLabel3.setBounds(50, 140, 9, 25);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel4.setText("<html>Usuario:</html>");
        izquierda.add(jLabel4);
        jLabel4.setBounds(50, 125, 50, 14);

        jLabel5.setBackground(new java.awt.Color(31, 184, 184));
        jLabel5.setOpaque(true);
        jLabel5.setPreferredSize(new java.awt.Dimension(9, 0));
        izquierda.add(jLabel5);
        jLabel5.setBounds(50, 200, 9, 25);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel6.setText("Contraseña:");
        izquierda.add(jLabel6);
        jLabel6.setBounds(50, 185, 70, 14);

        txtContraseña.setText("Ingresa una contraseña");
        txtContraseña.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtContraseñaFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtContraseñaFocusLost(evt);
            }
        });
        txtContraseña.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtContraseñaKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtContraseñaKeyTyped(evt);
            }
        });
        izquierda.add(txtContraseña);
        txtContraseña.setBounds(60, 200, 200, 25);

        notificacion.setForeground(new java.awt.Color(255, 51, 51));
        notificacion.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        izquierda.add(notificacion);
        notificacion.setBounds(10, 250, 280, 30);

        configuracion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagen/Sesion/configuracion-16.png"))); // NOI18N
        configuracion.setToolTipText("Configuración");
        configuracion.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        configuracion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                configuracionMouseClicked(evt);
            }
        });
        izquierda.add(configuracion);
        configuracion.setBounds(260, 5, 16, 16);

        minimizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagen/Sesion/minimizar-16.png"))); // NOI18N
        minimizar.setToolTipText("Minimizar");
        minimizar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        minimizar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                minimizarMouseClicked(evt);
            }
        });
        izquierda.add(minimizar);
        minimizar.setBounds(242, 5, 16, 16);

        lbcargar.setBackground(new java.awt.Color(45, 144, 54));
        lbcargar.setOpaque(true);
        izquierda.add(lbcargar);
        lbcargar.setBounds(0, 370, 300, 4);

        Mostrar.setBackground(new java.awt.Color(255, 255, 255));
        Mostrar.setText("Mostrar contraseña");
        Mostrar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Mostrar.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                MostrarItemStateChanged(evt);
            }
        });
        izquierda.add(Mostrar);
        Mostrar.setBounds(50, 230, 210, 23);

        autentificar.setText("Ingresar");
        autentificar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        autentificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                autentificarActionPerformed(evt);
            }
        });
        izquierda.add(autentificar);
        autentificar.setBounds(50, 270, 210, 40);

        getContentPane().add(izquierda);
        izquierda.setBounds(300, 0, 300, 374);

        derecha.setBackground(new java.awt.Color(153, 153, 255));
        derecha.setLayout(null);

        notificacionBD1.setBackground(new java.awt.Color(220, 24, 24));
        notificacionBD1.setInheritsPopupMenu(true);
        notificacionBD1.setLayout(null);

        jLabel9.setBackground(new java.awt.Color(220, 24, 24));
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("Error al intentar conectar a Base de Datos verifique su conexión");
        jLabel9.setPreferredSize(new java.awt.Dimension(500, 14));
        notificacionBD1.add(jLabel9);
        jLabel9.setBounds(0, 0, 600, 20);

        derecha.add(notificacionBD1);
        notificacionBD1.setBounds(0, 355, 600, 20);

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("<html>SCH</html>");
        derecha.add(jLabel7);
        jLabel7.setBounds(60, 154, 180, 70);

        SesionImagen.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagen/Sesion/animacion.gif"))); // NOI18N
        derecha.add(SesionImagen);
        SesionImagen.setBounds(-250, 0, 700, 374);

        getContentPane().add(derecha);
        derecha.setBounds(0, 0, 300, 374);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cerrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cerrarMouseClicked
        animacionCerrar();
        this.dispose();
        System.exit(0);
    }//GEN-LAST:event_cerrarMouseClicked

    private void minimizarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_minimizarMouseClicked
        this.setExtendedState(ICONIFIED);
    }//GEN-LAST:event_minimizarMouseClicked

    private void CerrarNotificacionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CerrarNotificacionMouseClicked
        notificacion(false);
    }//GEN-LAST:event_CerrarNotificacionMouseClicked

    private void configuracionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_configuracionMouseClicked
        new Configuracion(this, true);
    }//GEN-LAST:event_configuracionMouseClicked

    private void txtUsuarioFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtUsuarioFocusGained
        new ControladorCampos().limpiarCamposFocus(txtUsuario);
    }//GEN-LAST:event_txtUsuarioFocusGained

    private void txtContraseñaFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtContraseñaFocusGained
        new ControladorCampos().limpiarCamposFocus(txtContraseña);
    }//GEN-LAST:event_txtContraseñaFocusGained

    private void txtUsuarioFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtUsuarioFocusLost
        new ControladorCampos().configurarCampoFocus(txtUsuario, "Ingresa un usuario");
    }//GEN-LAST:event_txtUsuarioFocusLost

    private void txtContraseñaFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtContraseñaFocusLost
        new ControladorCampos().configurarCampoFocus(txtContraseña, "Ingresa una contraseña");
    }//GEN-LAST:event_txtContraseñaFocusLost

    private void txtUsuarioKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtUsuarioKeyTyped
        new ControladorLogitudCampos().limitarCaracteres(txtUsuario, evt, 20);
    }//GEN-LAST:event_txtUsuarioKeyTyped

    private void txtContraseñaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtContraseñaKeyTyped
        new ControladorLogitudCampos().limitarCaracteres(txtContraseña, evt, 15);
    }//GEN-LAST:event_txtContraseñaKeyTyped

    private void MostrarItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_MostrarItemStateChanged
        if (evt.getStateChange() == ItemEvent.SELECTED) {
            txtContraseña.setEchoChar((char) 0);
        } else {
            txtContraseña.setEchoChar('\u25cf');
        }
    }//GEN-LAST:event_MostrarItemStateChanged

    private void txtUsuarioKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtUsuarioKeyPressed
        if(evt.getKeyCode() == KeyEvent.VK_ENTER) {
            new Thread() {
                public void run() {
                    autentificacion();
                }
            }.start();
        }
    }//GEN-LAST:event_txtUsuarioKeyPressed

    private void txtContraseñaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtContraseñaKeyPressed
        if(evt.getKeyCode() == KeyEvent.VK_ENTER) {
            new Thread() {
                public void run() {
                    autentificacion();
                }
            }.start();
        }
    }//GEN-LAST:event_txtContraseñaKeyPressed

    private void autentificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_autentificarActionPerformed
        new Thread() {
            public void run() {
                autentificacion();
            }
        }.start();
    }//GEN-LAST:event_autentificarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Sesion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Sesion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Sesion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Sesion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Sesion().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel CerrarNotificacion;
    private javax.swing.JCheckBox Mostrar;
    private javax.swing.JLabel SesionImagen;
    private principal.MaterialButton autentificar;
    private javax.swing.JLabel cerrar;
    private javax.swing.JLabel configuracion;
    private javax.swing.JPanel derecha;
    private javax.swing.JPanel izquierda;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel lbcargar;
    private javax.swing.JLabel minimizar;
    private javax.swing.JLabel notificacion;
    private javax.swing.JPanel notificacionBD;
    private javax.swing.JPanel notificacionBD1;
    private javax.swing.JPasswordField txtContraseña;
    private javax.swing.JTextField txtUsuario;
    // End of variables declaration//GEN-END:variables
}
